// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/search-media.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
var TMDB_BASE_URL = "https://api.themoviedb.org/3";
var IMG = "https://image.tmdb.org/t/p/w342";
var search_media_default = defineTool({
  name: "search_media",
  title: "Search movies and TV shows",
  description: "Search TMDB for movies and TV shows by title. Returns up to 10 matches with id, type, title, year, rating, and overview.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Title to search for."),
    type: z.enum(["movie", "tv", "multi"]).optional().describe("Restrict results to movies, TV shows, or both (default: multi).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, type }) => {
    const apiKey = process.env.TMDB_API_KEY;
    if (!apiKey) {
      return { content: [{ type: "text", text: "TMDB API key not configured." }], isError: true };
    }
    const endpoint = type && type !== "multi" ? `search/${type}` : "search/multi";
    const url = `${TMDB_BASE_URL}/${endpoint}?api_key=${apiKey}&query=${encodeURIComponent(query)}&include_adult=false&page=1`;
    const res = await fetch(url);
    if (!res.ok) {
      return { content: [{ type: "text", text: `TMDB error: ${res.status}` }], isError: true };
    }
    const data = await res.json();
    const results = (data.results ?? []).filter((r) => r.poster_path && (r.media_type ?? type) !== "person").slice(0, 10).map((r) => {
      const mediaType = r.media_type ?? type ?? "movie";
      const title = r.title ?? r.name ?? "Untitled";
      const date = r.release_date ?? r.first_air_date ?? "";
      return {
        tmdb_id: r.id,
        type: mediaType,
        title,
        year: date ? date.slice(0, 4) : null,
        vote_average: r.vote_average ?? null,
        overview: r.overview ?? "",
        poster_url: r.poster_path ? `${IMG}${r.poster_path}` : null
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { results }
    };
  }
});

// src/lib/mcp/tools/get-watchlist.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_watchlist_default = defineTool2({
  name: "get_watchlist",
  title: "Get watchlist",
  description: "Return the signed-in user's watchlist items, optionally filtered by status (watchlist, watching, watched).",
  inputSchema: {
    status: z2.enum(["watchlist", "watching", "watched"]).optional().describe("Filter by status. Omit to return all items."),
    limit: z2.number().int().min(1).max(200).optional().describe("Max items to return (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("watchlist_items").select("tmdb_id, tmdb_type, title, release_date, vote_average, status, rating, watched_at, added_at").eq("user_id", ctx.getUserId()).order("added_at", { ascending: false }).limit(limit ?? 100);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-to-watchlist.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var TMDB_BASE_URL2 = "https://api.themoviedb.org/3";
var add_to_watchlist_default = defineTool3({
  name: "add_to_watchlist",
  title: "Add to watchlist",
  description: "Add a movie or TV show to the signed-in user's watchlist. Provide the TMDB id and type; title/metadata are fetched automatically.",
  inputSchema: {
    tmdb_id: z3.number().int().positive().describe("TMDB numeric id."),
    type: z3.enum(["movie", "tv"]).describe("Media type."),
    status: z3.enum(["watchlist", "watching", "watched"]).optional().describe("Initial status (default: watchlist).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ tmdb_id, type, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const apiKey = process.env.TMDB_API_KEY;
    if (!apiKey) {
      return { content: [{ type: "text", text: "TMDB API key not configured." }], isError: true };
    }
    const detailsRes = await fetch(`${TMDB_BASE_URL2}/${type}/${tmdb_id}?api_key=${apiKey}`);
    if (!detailsRes.ok) {
      return { content: [{ type: "text", text: `TMDB item not found (${detailsRes.status}).` }], isError: true };
    }
    const d = await detailsRes.json();
    const supabase = supabaseForUser2(ctx);
    const row = {
      user_id: ctx.getUserId(),
      tmdb_id,
      tmdb_type: type,
      title: d.title ?? d.name ?? "Untitled",
      poster_path: d.poster_path ?? null,
      release_date: d.release_date ?? d.first_air_date ?? null,
      vote_average: d.vote_average ?? null,
      status: status ?? "watchlist",
      runtime: d.runtime ?? d.episode_run_time?.[0] ?? null
    };
    const { data, error } = await supabase.from("watchlist_items").upsert(row, { onConflict: "user_id,tmdb_id,tmdb_type" }).select().maybeSingle();
    if (error) {
      const { data: existing } = await supabase.from("watchlist_items").select("id").eq("user_id", ctx.getUserId()).eq("tmdb_id", tmdb_id).eq("tmdb_type", type).maybeSingle();
      if (existing) {
        return { content: [{ type: "text", text: "Already in watchlist." }] };
      }
      const { error: insertError } = await supabase.from("watchlist_items").insert(row);
      if (insertError) {
        return { content: [{ type: "text", text: insertError.message }], isError: true };
      }
      return { content: [{ type: "text", text: `Added "${row.title}" to watchlist.` }] };
    }
    return {
      content: [{ type: "text", text: `Added "${row.title}" to watchlist.` }],
      structuredContent: { item: data }
    };
  }
});

// src/lib/mcp/tools/remove-from-watchlist.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.93.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var remove_from_watchlist_default = defineTool4({
  name: "remove_from_watchlist",
  title: "Remove from watchlist",
  description: "Remove a movie or TV show from the signed-in user's watchlist by TMDB id and type.",
  inputSchema: {
    tmdb_id: z4.number().int().positive(),
    type: z4.enum(["movie", "tv"])
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tmdb_id, type }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { error, count } = await supabase.from("watchlist_items").delete({ count: "exact" }).eq("user_id", ctx.getUserId()).eq("tmdb_id", tmdb_id).eq("tmdb_type", type);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: count && count > 0 ? "Removed." : "Item was not in watchlist." }]
    };
  }
});

// src/lib/mcp/tools/update-watchlist-item.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.93.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var update_watchlist_item_default = defineTool5({
  name: "update_watchlist_item",
  title: "Update watchlist item",
  description: "Update the status and/or personal rating of an existing watchlist item. Setting status to 'watched' stamps the watched_at time.",
  inputSchema: {
    tmdb_id: z5.number().int().positive(),
    type: z5.enum(["movie", "tv"]),
    status: z5.enum(["watchlist", "watching", "watched"]).optional(),
    rating: z5.number().min(1).max(10).nullable().optional().describe("Personal rating from 1-10. Pass null to clear.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ tmdb_id, type, status, rating }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const patch = {};
    if (status !== void 0) {
      patch.status = status;
      if (status === "watched") patch.watched_at = (/* @__PURE__ */ new Date()).toISOString();
    }
    if (rating !== void 0) patch.rating = rating;
    if (Object.keys(patch).length === 0) {
      return { content: [{ type: "text", text: "Nothing to update." }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const { data, error } = await supabase.from("watchlist_items").update(patch).eq("user_id", ctx.getUserId()).eq("tmdb_id", tmdb_id).eq("tmdb_type", type).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Item not found in watchlist." }], isError: true };
    return {
      content: [{ type: "text", text: `Updated "${data.title}".` }],
      structuredContent: { item: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wcbmcqfvvxwlksnakiuk";
var mcp_default = defineMcp({
  name: "watchlist-mcp",
  title: "Watchlist",
  version: "0.1.0",
  instructions: "Tools for the Watchlist app. Search TMDB movies and TV shows, then read and manage the signed-in user's watchlist (add, remove, update status and rating).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_media_default, get_watchlist_default, add_to_watchlist_default, remove_from_watchlist_default, update_watchlist_item_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
