// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/search-media.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/tmdb.ts
var TMDB_BASE_URL = "https://api.themoviedb.org/3";
var TMDB_TIMEOUT_MS = 8e3;
var TMDB_UNAVAILABLE_MESSAGE = "TMDB is unreachable or timed out";
function redactApiKey(text) {
  return text.replace(/api_key=[^&\s"')]+/gi, "api_key=REDACTED");
}
function tmdbFailed(result) {
  return !result.ok;
}
function describe(err) {
  return redactApiKey(err instanceof Error ? `${err.name}: ${err.message}` : String(err));
}
async function tmdbGet(path, params = {}) {
  const apiKey = process.env.TMDB_API_KEY;
  if (!apiKey) return { ok: false, kind: "config", message: "TMDB API key not configured." };
  const query = new URLSearchParams({ api_key: apiKey, ...params });
  let res;
  try {
    res = await fetch(`${TMDB_BASE_URL}/${path}?${query}`, { signal: AbortSignal.timeout(TMDB_TIMEOUT_MS) });
  } catch (err) {
    console.error("[mcp] TMDB request failed:", describe(err));
    return { ok: false, kind: "network", message: TMDB_UNAVAILABLE_MESSAGE };
  }
  if (!res.ok) return { ok: false, kind: "http", status: res.status, message: `TMDB error: ${res.status}` };
  try {
    return { ok: true, data: await res.json() };
  } catch (err) {
    console.error("[mcp] TMDB response unreadable:", describe(err));
    const timedOut = err instanceof Error && (err.name === "TimeoutError" || err.name === "AbortError");
    return {
      ok: false,
      kind: timedOut ? "network" : "parse",
      message: timedOut ? TMDB_UNAVAILABLE_MESSAGE : "TMDB returned an unexpected response"
    };
  }
}
function toolError(text) {
  return { content: [{ type: "text", text }], isError: true };
}

// src/lib/mcp/tools/search-media.ts
var IMG = "https://image.tmdb.org/t/p/w342";
var search_media_default = defineTool({
  name: "search_media",
  title: "Search movies and TV shows",
  description: "Search TMDB for movies and TV shows by title. Returns up to 10 matches with id, type, title, year, rating, and overview.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Title to search for."),
    type: z.enum(["movie", "tv", "multi"]).optional().describe("Restrict results to movies, TV shows, or both (default: multi).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, type }) => {
    const endpoint = type && type !== "multi" ? `search/${type}` : "search/multi";
    const res = await tmdbGet(endpoint, {
      query,
      include_adult: "false",
      page: "1"
    });
    if (tmdbFailed(res)) return toolError(res.message);
    const data = res.data;
    const results = (data.results ?? []).filter((r) => r.poster_path && (r.media_type ?? type) !== "person").slice(0, 10).map((r) => {
      const mediaType = r.media_type ?? type ?? "movie";
      const title = r.title ?? r.name ?? "Untitled";
      const date = r.release_date ?? r.first_air_date ?? "";
      return {
        tmdb_id: r.id,
        type: mediaType,
        title,
        year: date ? date.slice(0, 4) : null,
        vote_average: r.vote_average ?? null,
        overview: r.overview ?? "",
        poster_url: r.poster_path ? `${IMG}${r.poster_path}` : null
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { results }
    };
  }
});

// src/lib/mcp/tools/get-watchlist.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.1";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  if (!url || !key) throw new Error("Supabase is not configured for this function");
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-watchlist.ts
var get_watchlist_default = defineTool2({
  name: "get_watchlist",
  title: "Get watchlist",
  description: "Return the signed-in user's Reel list, optionally filtered by status ('watchlist' = to watch, 'watched').",
  inputSchema: {
    status: z2.enum(["watchlist", "watched"]).optional().describe("Filter by status. Omit to return all items."),
    limit: z2.number().int().min(1).max(200).optional().describe("Max items to return (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("watchlist_items").select("tmdb_id, tmdb_type, title, release_date, vote_average, status, rating, watched_at, added_at").eq("user_id", ctx.getUserId()).order("added_at", { ascending: false }).limit(limit ?? 100);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-to-watchlist.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
var add_to_watchlist_default = defineTool3({
  name: "add_to_watchlist",
  title: "Add to watchlist",
  description: "Add a movie or TV show to the signed-in user's list in Reel. Provide the TMDB id and type; title/metadata are fetched automatically. If the title is already in the list it is left unchanged.",
  inputSchema: {
    tmdb_id: z3.number().int().positive().describe("TMDB numeric id."),
    type: z3.enum(["movie", "tv"]).describe("Media type."),
    status: z3.enum(["watchlist", "watched"]).optional().describe("Initial status (default: watchlist).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ tmdb_id, type, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const details = await tmdbGet(`${type}/${tmdb_id}`);
    if (tmdbFailed(details)) {
      return toolError(details.kind === "http" ? `TMDB item not found (${details.status}).` : details.message);
    }
    const d = details.data;
    const supabase = supabaseForUser(ctx);
    const row = {
      user_id: ctx.getUserId(),
      tmdb_id,
      tmdb_type: type,
      title: d.title ?? d.name ?? "Untitled",
      poster_path: d.poster_path ?? null,
      release_date: d.release_date ?? d.first_air_date ?? null,
      vote_average: d.vote_average ?? null,
      status: status ?? "watchlist",
      watched_at: status === "watched" ? (/* @__PURE__ */ new Date()).toISOString() : null,
      runtime: d.runtime ?? d.episode_run_time?.[0] ?? null
    };
    const { data, error } = await supabase.from("watchlist_items").upsert(row, { onConflict: "user_id,tmdb_id,tmdb_type", ignoreDuplicates: true }).select().maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Already in your list." }] };
    }
    return {
      content: [{ type: "text", text: `Added "${row.title}" to your list.` }],
      structuredContent: { item: data }
    };
  }
});

// src/lib/mcp/tools/remove-from-watchlist.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
var remove_from_watchlist_default = defineTool4({
  name: "remove_from_watchlist",
  title: "Remove from watchlist",
  description: "Remove a movie or TV show from the signed-in user's Reel list by TMDB id and type.",
  inputSchema: {
    tmdb_id: z4.number().int().positive(),
    type: z4.enum(["movie", "tv"])
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tmdb_id, type }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { error, count } = await supabase.from("watchlist_items").delete({ count: "exact" }).eq("user_id", ctx.getUserId()).eq("tmdb_id", tmdb_id).eq("tmdb_type", type);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: count && count > 0 ? "Removed." : "Item was not in your list." }]
    };
  }
});

// src/lib/mcp/tools/update-watchlist-item.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^3.25.76";
var update_watchlist_item_default = defineTool5({
  name: "update_watchlist_item",
  title: "Update watchlist item",
  description: "Update the status ('watchlist' = to watch, 'watched') and/or personal rating of an existing item in the user's Reel list. Marking an item watched stamps watched_at (unless it was already watched); moving it back to 'watchlist' clears it.",
  inputSchema: {
    tmdb_id: z5.number().int().positive(),
    type: z5.enum(["movie", "tv"]),
    status: z5.enum(["watchlist", "watched"]).optional(),
    rating: z5.number().min(1).max(10).nullable().optional().describe("Personal rating from 1-10. Pass null to clear.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ tmdb_id, type, status, rating }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    if (status === void 0 && rating === void 0) {
      return { content: [{ type: "text", text: "Nothing to update." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const patch = {};
    if (status !== void 0) {
      patch.status = status;
      if (status === "watched") {
        const { data: current, error: readError } = await supabase.from("watchlist_items").select("status, watched_at").eq("user_id", ctx.getUserId()).eq("tmdb_id", tmdb_id).eq("tmdb_type", type).maybeSingle();
        if (readError) return { content: [{ type: "text", text: readError.message }], isError: true };
        if (!current) return { content: [{ type: "text", text: "Item not found in your list." }], isError: true };
        if (!(current.status === "watched" && current.watched_at)) {
          patch.watched_at = (/* @__PURE__ */ new Date()).toISOString();
        }
      } else {
        patch.watched_at = null;
      }
    }
    if (rating !== void 0) patch.rating = rating;
    const { data, error } = await supabase.from("watchlist_items").update(patch).eq("user_id", ctx.getUserId()).eq("tmdb_id", tmdb_id).eq("tmdb_type", type).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Item not found in your list." }], isError: true };
    return {
      content: [{ type: "text", text: `Updated "${data.title}".` }],
      structuredContent: { item: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yaedljfsgtyuoknklejy";
var mcp_default = defineMcp({
  name: "reel-mcp",
  title: "Reel",
  version: "0.1.0",
  instructions: "Tools for the Reel app. Search TMDB movies and TV shows, then read and manage the signed-in user's list (add, remove, update status and rating). Status is either 'watchlist' (to watch) or 'watched'.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_media_default, get_watchlist_default, add_to_watchlist_default, remove_from_watchlist_default, update_watchlist_item_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
